name: Build and deploy dotnet core app to Azure Function App - bookstore-test 

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_VERSION: '9.0.x'
  SOLUTION_FILE_PATH: 'Libropedia.sln'
  FUNCTION_APP_PROJECT_PATH: 'Libropedia.csproj' 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Clean Solution'
        run: dotnet clean ${{ env.SOLUTION_FILE_PATH }} --configuration Release

      # - name: 'Restore Dependencies for Solution'
      #   run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}

      - name: 'Run Tests'
        run: dotnet test ${{ env.SOLUTION_FILE_PATH }} --configuration Release --logger "trx;LogFileName=test_results.trx"

      - name: 'Publish Test Results'
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: '**/*.trx'
          retention-days: 7
          if-no-files-found: warn

      - name: 'Publish Azure Functions Project'
        run: dotnet publish ${{ env.FUNCTION_APP_PROJECT_PATH }} --configuration Release --output ./output --self-contained false 

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_030DBD2EB16542FB9BF29C5BB2A1DBD3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C7494FA1BBE9407C8D593F062314A3E8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_469BFFACAD854D1886B456969756E1D9 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'bookstore-test'
          slot-name: 'Production'
          package: 'output'
